sudo: required
language: generic 

services:
  - docker

before_install:
  - docker build -t shankarkool/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true shankarkool/docker-react npm run test -- --coverage 